/*
 * Every word the app shows, in one place.
 *
 * STRINGS.en holds the English and STRINGS.he the Hebrew, with the same keys;
 * a key missing from the Hebrew falls back to English. The language is chosen
 * in Settings (kept in localStorage "learning-calendar-language").
 * In the page, an element with data-t="key" gets that text, data-t-html="key"
 * gets it as HTML (for a link or bold word inside), and data-t-placeholder,
 * data-t-aria-label and data-t-title fill those attributes. In code: tr("key")
 * or tr("key", { n: 3 }) for "{n}" inside the text.
 */
(function (global) {
  "use strict";
  const STRINGS = { en: {
    // app
    "app.learningCalendar": "שעשועי",
    "app.notSavedOnThis": "Not saved on this phone. The phone's storage may be full or blocked; your latest changes will be lost when the app closes.",
    "app.notSavedToAn": "Not saved to an account yet.",
    "app.signIn": "Sign in",

    // gate
    "gate.signInToStart": "Sign in to start. Your plans and progress are saved to your account after every change, and are the same on every phone and computer.",
    "gate.continueWithGoogle": "Continue with Google",
    "gate.orGetASign": "Or get a sign-in link by email",
    "gate.youExampleCom": "you@example.com",
    "gate.emailMeASign": "Email me a sign-in link",
    "gate.whatWeKeep": "What we keep",
    "gate.yourEmailAddressAnd": "Your email address and your learning plans, only to show them to you. Nothing is sold or shared. We may show counts of how many people learn each sefer, never who they are. Your name or learning is shown to others only if you turn that on in Settings. You can delete your account and everything in it from Settings.",
    "gate.notNow": "Not now",

    // today
    "today.loading": "Loading…",
    "today.today": "Today",
    "today.addASefer": "Add a sefer",
    "today.thisWeek": "This week",
    "today.startYourFirstSefer": "Start your first sefer",
    "today.chooseASeferAnd": "Choose a sefer and how you want to learn it. Each day you get where to start and where to stop in your own sefer.",
    "today.chooseASefer": "Choose a sefer",

    // library
    "library.learningNow": "Learning now",
    "library.seforim": "Seforim",
    "library.nothingYet": "Nothing yet",
    "library.seforimYouLearnWill": "Seforim you learn will be listed here with their progress.",

    // plan
    "plan.previousMonth": "Previous month",
    "plan.nextMonth": "Next month",
    "plan.done": "Done",
    "plan.toLearn": "To learn",
    "plan.off": "Off",
    "plan.changeThePlan": "Change the plan",
    "plan.finishBy": "Finish by",
    "plan.daysOffFrom": "Days off from",
    "plan.until": "until",
    "plan.saveChanges": "Save changes",
    "plan.daysAlreadyDoneStay": "Days already done stay as they are. What is left is shared out again.",
    "plan.daysOfThePlan": "Days of the plan",
    "plan.stopLearningThisSefer": "Stop learning this sefer",

    // settings
    "settings.settings": "Settings",
    "settings.account": "Account",
    "settings.notSignedInYour": "Not signed in. Your plans are kept on this phone only until you sign in.",
    "settings.signedInAs": "Signed in as",
    "settings.yourPlansAreSaved": "Your plans are saved to your account after every change.",
    "settings.displayNameOptional": "Display name (optional)",
    "settings.howOtherLearnersWould": "How other learners would see you",
    "settings.letOtherLearnersSee": "Let other learners see what I'm learning",
    "settings.offUnlessYouTurn": "Off unless you turn it on. Nothing is shown to anyone yet; this is for features coming later.",
    "settings.signOut": "Sign out",
    "settings.deleteAccount": "Delete account",
    "settings.privacy": "Privacy",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.automatic": "Automatic",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.style": "Style",
    "settings.solid": "Solid",
    "settings.glass": "Glass",
    "settings.color": "Color",
    "settings.dailyReminder": "Daily reminder",
    "settings.aReminderFromYour": "A reminder from your phone's own calendar on your learning days. It opens the app, which shows the day's place.",
    "settings.time": "Time",
    "settings.addToMyCalendar": "Add to my calendar",
    "settings.onIphoneAndIpad": "On iPhone and iPad, tap “Add All” on the next screen. On Android, open the file with your calendar app and tap Add or Import.",
    "settings.sectionNames": "Section names",
    "settings.hebrew": "Hebrew",
    "settings.english": "English",
    "settings.forSeforimDividedInto": "For seforim divided into named sections, like Chovos HaLevavos: <bdi lang=\"he\" dir=\"rtl\">שער ראשון - שער ייחוד ג</bdi> or First Treatise on Unity 3.",
    "settings.exportAndImport": "Export and import",
    "settings.aCopyOfYour": "A copy of your plans as a file, to keep or to move by hand. Not needed when you are signed in.",
    "settings.export": "Export",
    "settings.importAFile": "Import a file",
    "settings.ifNoFileWas": "If no file was saved, copy this text and keep it somewhere safe, for example in an email to yourself.",
    "settings.copyBackupText": "Copy backup text",
    "settings.loadABackupFrom": "Load a backup from copied text",
    "settings.pasteTheBackupText": "Paste the backup text here",
    "settings.loadThisBackup": "Load this backup",
    "settings.aboutAndSources": "About and sources",

    // privacy
    "privacy.ifYouSignIn": "If you sign in to שעשועי, we store your email address, a display name if you choose one, and your learning plans: which seforim, your settings, and a record of each day you learned, missed or moved.",
    "privacy.weKeepThemOnly": "We keep them only to show them back to you, on any phone or computer where you sign in. Nothing is sold, and nothing is shared with anyone.",
    "privacy.theyAreKeptWith": "They are kept with Google Firebase, the service that runs the sign-in and the saving. Each account can reach only its own plans.",
    "privacy.ifYouDoNot": "If you do not sign in, nothing leaves your phone: your plans are kept in this browser only.",
    "privacy.weMayShowCounts": "We may show counts of how many people learn each sefer, never who they are.",
    "privacy.weOnlyShowYour": "Showing your name or what you are learning to other learners is coming later. It will happen only if you turn on \"Let other learners see what I'm learning\" in Settings, which is off unless you turn it on.",
    "privacy.youCanDeleteYour": "You can delete your account and all your plans at any time: Settings, then Delete account.",

    // about
    "about.about": "About שעשועי",
    "about.eachDayTheApp": "Each day שעשועי shows where to start and where to stop in your own printed sefer, named the way printed learning calendars name it: the amud, mishnah, pasuk, halacha, se'if or siman, and the first few words where the day stops. Days are sized by your settings, counting the commentaries you learn together with the text.",
    "about.sources": "Sources",
    "about.theSizesOfThe": "The sizes of the days and the few words that name each place come from texts published by <a href=\"https://www.sefaria.org\" target=\"_blank\" rel=\"noopener\">Sefaria</a>, using only Public Domain editions, except these two:",
    "about.theGemaraSText": "The Gemara's text: <b>Wikisource Talmud Bavli</b> (<bdi lang=\"he\" dir=\"rtl\">תלמוד בבלי, ויקיטקסט</bdi>), licensed <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY-SA</a>, from <a href=\"https://he.wikisource.org/wiki/%D7%AA%D7%9C%D7%9E%D7%95%D7%93_%D7%91%D7%91%D7%9C%D7%99\" target=\"_blank\" rel=\"noopener\">he.wikisource.org</a>. The app keeps only the first few words of each place in it.",
    "about.everyEditionAndIts": "Every edition and its license",

    // add
    "add.cancel": "Cancel",
    "add.1Of3": "1 of 3",
    "add.searchInEnglishOr": "Search in English or Hebrew",
    "add.collections": "Collections",
    "add.selectAllAvailable": "Select all available",
    "add.clear": "Clear",
    "add.learnTogetherWith": "Learn together with",
    "add.onlyPartOfThe": "Only part of the sefer",
    "add.from": "From",
    "add.to": "To",
    "add.setYourPace": "Set your pace",
    "add.howMuch": "How much",
    "add.dailyAmount": "Daily amount",
    "add.timeADay": "Time a day",
    "add.finishOn": "Finish on",
    "add.theSeferIsShared": "The sefer is shared out evenly until then.",
    "add.eachDay": "Each day",
    "add.less": "Less",
    "add.amud": "amud",
    "add.more": "More",
    "add.minutes": "minutes",
    "add.myPace": "My pace",
    "add.slower": "Slower",
    "add.average": "Average",
    "add.faster": "Faster",
    "add.daysILearn": "Days I learn",
    "add.lighterDay": "Lighter day",
    "add.fri": "Fri",
    "add.aShorterDayAbout": "A shorter day, about two-thirds of a usual day, for example before Shabbos.",
    "add.startOn": "Start on",
    "add.daysOff": "Days off",
    "add.reasonOptional": "Reason (optional)",
    "add.vacationYomTov": "Vacation, Yom Tov…",
    "add.addDaysOff": "Add days off",
    "add.yourPlan": "Your plan",
    "add.next": "Next",
    "add.startLearning": "Start learning",

    // app
    "app.screens": "Screens",

    // missed
    "missed.youMissedADay": "You missed a day",
    "missed.pushTheFinishDate": "Push the finish date later",
    "missed.spreadItOverThe": "Spread it over the coming days",
    "missed.doubleUpOnThe": "Double up on the next day",

    // ask
    "ask.yes": "Yes",

    // added in code (app.js, accounts.js)
    "today.addTime": "How many minutes did it take? (optional)",
    "today.timeSaved": "Saved with this day",
    "reminder.title": "Time to learn",
    "reminder.description": "Open שעשועי to see today's place: {url}",
    "reminder.noDays": "No days left for a reminder: only Shabbos, Yom Tov or Friday evenings",
    "day.0": "Sun",
    "day.1": "Mon",
    "day.2": "Tue",
    "day.3": "Wed",
    "day.4": "Thu",
    "day.5": "Fri",
    "day.6": "Shabbos",
    "unit.pasuk": "pasuk",
    "unit.pasuk.many": "pesukim",
    "unit.mishnah": "mishnah",
    "unit.mishnah.many": "mishnayos",
    "unit.amud": "amud",
    "unit.amud.many": "amudim",
    "unit.halacha": "halacha",
    "unit.halacha.many": "halachos",
    "unit.seif": "se'if",
    "unit.seif.many": "se'ifim",
    "unit.siman": "siman",
    "unit.siman.many": "simanim",
    "unit.section": "section",
    "unit.section.many": "sections",
    "name.someOf": "{col}: {n} of {total}",
    "settings.anyColor": "Any color",
    "settings.colorN": "Color {color}",
    "settings.namesHe": "Section names in Hebrew",
    "settings.namesEn": "Section names in English",
    "route.fromWords": "{place}, from the words",
    "route.beginningOf": "the beginning of {place}",
    "route.untilWords": "{place}, until the words",
    "route.endOf": "the end of {place}",
    "route.commSeifKatan": "{name} through {siman}se'if katan {n}",
    "route.simanN": "siman {n}, ",
    "route.commThrough": "{name} through",
    "route.start": "Start",
    "route.stop": "Stop",
    "today.nothingNew": "Nothing new to learn on this day.",
    "today.allDoneToday": "All done for today. Yasher koach!",
    "today.allDone": "All done. Yasher koach!",
    "today.stillToLearn": "{n} of {all} still to learn",
    "part.title": "Where did you stop?",
    "part.saved": "Saved. Next time starts where you stopped.",
    "save.notOnPhone": "Marked, but not saved on this phone",
    "missed.cantToday": "Can't learn today",
    "missed.missedMany": "You missed {n} days",
    "missed.missedOne": "You missed a day",
    "missed.whatToday": "What should happen to today's portion?",
    "missed.whatMissed": "What should happen to the portions you missed?",
    "missed.done.push": "The finish date moved later",
    "missed.done.spread": "Spread over the coming days",
    "missed.done.double": "Added to the next day",
    "today.yasherKoach": "Yasher koach!",
    "load.aSefer": "A sefer",
    "load.failed": "Could not load this sefer. Your progress in it is kept. Check the connection and try again.",
    "load.retry": "Retry",
    "load.still": "Still could not load it",
    "library.daysDone": "{n} of {all} days",
    "library.behind": "{n} behind",
    "plan.aboutMinutes": "about {n} minutes a day",
    "plan.daysDone": "days done",
    "plan.onTrack": "On track",
    "plan.aheadBy": "ahead by {n}",
    "plan.status": "status",
    "plan.finishingYear": "finishing {year}",
    "plan.finishing": "finishing",
    "plan.daysIn": "Days in {month}",
    "plan.noNewLearning": "No new learning",
    "plan.unmark": "Done; tap to unmark",
    "plan.noDaysThisMonth": "No days of this plan in this month.",
    "cal.done": "done",
    "cal.notInPlan": "Not part of the plan.",
    "cal.noNew": "No new learning.",
    "plan.updated": "Plan updated",
    "plan.stopAsk": "Stop learning {name}? Its progress will be removed.",
    "plan.stopYes": "Stop learning it",
    "day.short.0": "Su",
    "day.short.1": "Mo",
    "day.short.2": "Tu",
    "day.short.3": "We",
    "day.short.4": "Th",
    "day.short.5": "Fr",
    "day.short.6": "Sh",
    "add.stepOf": "{n} of 3",
    "add.back": "Back",
    "collection.note.bavli": "Rashi and Tosafot on Sanhedrin are not included: there is no free edition. Tamid has no Rashi or Tosafot on Sefaria.",
    "collection.note.yerushalmi": "Named by perek and halacha, which match every printed Yerushalmi (daf numbers differ between printings). From Guggenheimer's edition.",
    "collection.note.rambam": "Not included, because there is no free edition: Hilchos Tefillin, Mezuzah and Sefer Torah; Tzitzis; Berachos; Milah; and the Order of Prayers.",
    "collection.note.shulchan-aruch": "Mishnah Berurah on Orach Chaim simanim 1 to 186 is estimated: the free edition does not have them, so their length is estimated from the number of se'ifim katanim.",
    "collection.note.halacha": "Not included, because there is no free edition: Aruch HaShulchan Orach Chaim, Shulchan Aruch HaRav.",
    "collection.note.mussar": "Not included, because there is no free edition: Tanya, Chofetz Chaim, Shemiras HaLashon, Orchos Tzaddikim, Kuzari, Sefer HaChinuch.",
    "collection.note.midrash": "Not included, because there is no free edition: Zohar, Mechilta.",
    "add.nothingMatches": "Nothing matches.",
    "add.oneChosen": "{name} chosen",
    "add.allChosen": "All {n} available chosen",
    "add.nChosen": "{n} chosen",
    "add.rangeHint": "Write it as in the sefer, for example {example}.",
    "add.endBeforeStart": "The end comes before the start.",
    "add.none": "None",
    "add.chooseSome": "Choose one or more seforim",
    "add.timeHint": "At this pace the whole of it takes about {n} hours of learning.",
    "add.summary": "{n} days · finishing {date}",
    "add.days": "days",
    "add.aboutMinutes": "About {n} minutes a day",
    "add.learnWith": "Learn with",
    "add.textAlone": "The text alone",
    "add.reviewDays": "Days",
    "add.lighterX": "lighter {day}",
    "add.starting": "Starting",
    "add.firstDay": "First day, {date}",
    "add.chooseFirstOff": "Choose the first day off",
    "add.remove": "Remove",
    "reminder.addFirst": "Add a sefer first; the reminder follows your plans.",
    "reminder.days": "On {days}, the days you learn, until {date}, when your last sefer is finished. Never on Shabbos or Yom Tov, and with an evening time not on Friday or Erev Yom Tov. If a plan changes, add it again.",
    "reminder.addSeferFirst": "Add a sefer first",
    "backup.copied": "Backup copied",
    "backup.selectAndCopy": "Select the text and copy it",
    "backup.notBackup": "This is not a שעשועי backup.",
    "backup.replaceAsk": "Replace the {n} plans on this phone with the {m} in the backup?",
    "backup.replace": "Replace",
    "backup.partFailed": "Part of this backup could not be read. Nothing was changed.",
    "backup.loaded": "Backup loaded",
    "load.catalogFailed": "Could not load the list of sefarim ({error}). Check the connection and try again.",
    "lesson.with": "with {names}",
    "lesson.day": "day",
    "lesson.finishing": "Finishing {date}",
    "lesson.wholeSchedule": "Whole schedule",
    "lesson.catchUp": "Catch up",
    "lesson.cantToday": "I can't learn today",
    "lesson.siyum": "Finished the whole sefer. Mazal tov!",
    "lesson.undoLast": "Undo the last day",
    "lesson.fromDate": "From {date}",
    "lesson.markDone": "Mark as done",
    "lesson.openSefaria": "Open on Sefaria",
    "lesson.onlyPart": "I only did part of it",
    "lesson.undo": "Undo",
    "lesson.done": "Done",
    "lesson.doneToday": "Done for today",
    "lesson.noLearning": "No learning on this day.",
    "lesson.next": "Next, {date}:",
    "lesson.learnAhead": "Learn ahead: mark {date} done",
    "status.finished": "Finished",
    "status.behindOne": "1 day behind",
    "status.behindMany": "{n} days behind",
    "status.ahead": "Ahead by {n}",
    "status.onSchedule": "On schedule",
    "added": "{name} added",
    "ask.save": "Save",
    "plan.paused": "Paused",
    "plan.pausedSince": "Paused since {date}. When you resume, the finish date moves later by the days paused.",
    "plan.resume": "Resume",
    "plan.resumed": "Resumed. What is left is shared out from today.",
    "group.summary": "{n} seforim together · finishing {date}",
    "group.pause": "Pause all",
    "group.resume": "Resume all",
    "group.pausedToast": "Paused. Nothing is due until you resume.",
    "group.move": "Move the finish date",
    "group.moveTitle": "New finish date for the whole group",
    "group.moved": "All of them now finish {date}",
    "group.changeOnToday": "This sefer is part of a group. Pause it or move its finish date together with the others, on the Today screen.",
    "kol.title": "Kol HaTorah in a year",
    "kol.short": "Shas, Mishnah, Rambam, Tanach and Shulchan Aruch, all finishing on the same day",
    "kol.intro": "One plan for each, all starting and finishing on the same dates. Remove any, or add another sefer.",
    "kol.optional": "optional",
    "kol.addOther": "Add another sefer",
    "kol.chooseOne": "Choose at least one.",
    "kol.endAfterStart": "The finish date must come after the start.",
    "kol.summary": "{n} plans, from {start} to {end}, each shared out evenly by its size.",
    "kol.create": "Start Kol HaTorah",
    "kol.making": "Preparing…",
    "kol.made": "{n} plans started together",
    "cycles.title": "Join a daily cycle",
    "cycles.short": "Daf Yomi, Mishnah Yomit or Rambam Yomi, learning what everyone learns today",
    "cycles.intro": "In a cycle everyone learns the same thing on the same day, so the days follow the cycle, not your settings.",
    "cycles.note.daf-yomi": "One daf a day",
    "cycles.note.mishnah-yomit": "Two mishnayos a day",
    "cycles.note.rambam-3": "Three perakim a day",
    "cycles.note.rambam-1": "One perek a day",
    "cycles.today": "Today: {name}",
    "cycles.ends": "This cycle finishes {date}",
    "cycles.join": "Join",
    "cycles.joined": "Joined",
    "cycles.welcome": "You joined {name}",
    "cycle.pill": "Daily cycle",
    "cycle.openPlace": "Open on Sefaria",
    "cycle.placeOnly": "Not in the app's texts: learn it from your own sefer.",
    "cycle.noChanges": "A daily cycle follows the cycle's own dates: everyone learns the same thing on the same day, so its days cannot be changed.",
    "review.pill": "Review",
    "review.switch": "This is a review (chazara)",
    "review.note": "Marked as review, at its own pace. Your first learning of it stays as it was.",
    "review.start": "Review what I learned (chazara)",
    "review.nothingYet": "Mark some days done first",
    "dedication.title": "Dedication (optional)",
    "dedication.none": "None",
    "dedication.iluiNishmas": "L'ilui nishmas",
    "dedication.refuah": "L'refuah shleimah",
    "dedication.namePlaceholder": "Name, e.g. Ploni ben Ploni",
    "dedication.save": "Save the dedication",
    "dedication.saved": "Dedication saved",
    "dedication.lineIlui": "l'ilui nishmas",
    "dedication.lineRefuah": "l'refuah shleimah",
    "suggest.title": "Before {name}",
    "suggest.sub": "Finish by Erev Yom Tov, {date}",
    "suggest.start": "Start",
    "suggest.hide": "Not this year",
    "suggest.noRange": "That part is not in the app",
    "account.framed": "Signing in works on the website, sefer-calendar.web.app, not in this preview. Plans here are kept on this phone only.",
    "account.offline": "Signing in needs a connection. Your plans are kept on this phone meanwhile, and move into your account when you sign in.",
    "account.linkSent": "We sent a sign-in link to {email}. Open it on this phone to sign in.",
    "account.typeEmail": "To finish signing in on this phone, type the email address the link was sent to, then tap Finish signing in.",
    "account.error.invalid-email": "That email address does not look right.",
    "account.error.network-request-failed": "No connection. Try again when the phone is online.",
    "account.error.invalid-action-code": "This sign-in link was already used or is too old (links work once, for about an hour). Type your email to get a new one.",
    "account.error.expired-action-code": "This sign-in link is too old (links work for about an hour). Type your email to get a new one.",
    "account.error.unauthorized-domain": "Signing in is not set up for this web address yet.",
    "account.error.operation-not-allowed": "This way of signing in is not turned on yet.",
    "account.error.other": "Could not sign in ({code}).",
    "account.yours": "your account",
    "account.unreachable": "Could not reach your account. Changes are kept on this phone and sent later.",
    "account.uploadedMany": "{n} plans from this phone saved to your account",
    "account.uploadedOne": "1 plan from this phone saved to your account",
    "account.saveFailed": "Could not save to your account. Changes are kept on this phone and sent later.",
    "account.nameSaved": "Name saved",
    "account.signedOut": "Signed out. Your plans stay in your account.",
    "account.deleteAsk": "Delete your account and all your plans? This cannot be undone.",
    "account.deleteYes": "Delete everything",
    "account.signInAgain": "For your safety, please sign in again, then delete.",
    "account.deleted": "Your account and plans were deleted.",
    "account.deleteFailed": "Could not delete the account. Try again when online.",
    "engine.siman": "siman {n}",
    "engine.time.2": " (the second time)",
    "engine.time.3": " (the third time)",
    "engine.time.4": " (the fourth time)",
    "engine.time.5": " (the fifth time)",
    "engine.time.6": " (the sixth time)",
    "engine.time.7": " (the seventh time)",
    "engine.time.8": " (the eighth time)",
    "engine.time.9": " (the ninth time)",
    "engine.time.10": " (the tenth time)",
    "engine.time.n": " (the {n}th time)",
    "engine.simanComma": "siman {n}, ",
    "engine.seifKatan": "{name} through {siman}se'if katan {n}",
    "engine.commThrough": "{name} through “{words}”",
    "engine.commOn": "{name} on {place}",
    "engine.fromWords": ", from the words “{words}”{time}",
    "engine.untilWords": ", until the words “{words}”{time}",
    "engine.toTheEndComma": ", to the end of {place}",
    "engine.aToB": "{a} to {b}",
    "engine.simanim": "simanim {a}–{b}",
    "engine.theEndOf": "the end of {place}",
    "engine.hasNo": "{name} has no {place}",
    "engine.whichSefer": "Write which sefer, for example {example}",
    "engine.noDaysSet": "No learning days are set",
    "engine.noDaysBefore": "There are no learning days before the finish date",
    "engine.tooSmall": "The daily amount is too small",
    "engine.outside": "The start and end are outside the sefer",
    "engine.oneDay": "Choose at least one learning day",
    "engine.endBeforeStart": "The finish date is before the start",
    "engine.chooseHow": "Choose a finish date, a daily amount or the minutes you have each day",
    "engine.insideDay": "Choose a place inside that day",
    "about.yerushalmi": "The Yerushalmi's text: <b>The Jerusalem Talmud, edition by Heinrich W. Guggenheimer</b> (Berlin, De Gruyter, 1999-2015), licensed <a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY</a>, via <a href=\"https://www.sefaria.org/texts/Talmud/Yerushalmi\" target=\"_blank\" rel=\"noopener\">Sefaria</a>. The app keeps only the first few words of each place in it, and names places by perek and halacha.",
    "add.skipYomTov": "Leave out Yom Tov",
    "add.yomTovIsrael": "No learning on Yom Tov, one day as in Israel (from this phone's time zone). Chol HaMoed stays a learning day.",
    "add.yomTovOutside": "No learning on Yom Tov, two days as outside Israel (from this phone's time zone). Chol HaMoed stays a learning day.",
    "export.button": "Add every day to my calendar",
    "export.note": "Each learning day as an all-day event with its place and Sefaria link. After a change, add it again: the days are updated, not doubled.",
    "export.summary": "{name}: day {n} of {all}",
    "print.button": "Print this week",
    "print.title": "Learning for {from} – {to}",
    "print.nothing": "No learning",
    "print.foot": "From שעשועי, sefer-calendar.web.app. Tick each box when done.",
    "share.button": "Learn with a chavrusa",
    "share.again": "Send the chavrusa link again",
    "share.howTo": "Send this link. Your chavrusa opens it, signs in, and gets the same schedule. You each see how far the other is.",
    "share.send": "Send",
    "share.copy": "Copy link",
    "share.copied": "Link copied",
    "share.message": "Let's learn {name} together. Open this link to join:",
    "share.signInFirst": "Sign in first, so the plan can be shared",
    "share.someone": "A chavrusa",
    "share.notFound": "This chavrusa link could not be opened. Ask for a new one.",
    "share.joinAsk": "Learn {name} together with {who}? You get the same schedule, and you each see how far the other is.",
    "share.join": "Learn together",
    "share.joined": "You are learning together with {who}",
    "share.waiting": "Shared with a chavrusa: waiting for them to join",
    "share.progress": "{done} of {total} days",
    "share.doneToday": "done today",
    "share.lastDone": "last done {date}",
    "privacy.sharing": "If you share a plan with a chavrusa, anyone you send the link to can see that plan's schedule, your display name and how many days you have done in it. Nothing else is shared.",
    "settings.language": "Language",
    "settings.languageNote": "The language of the screens. The seforim's names are in Hebrew either way.",
    "settings.langEnglish": "English",
    "settings.langHebrew": "עברית",
    "sync.conflict": "A plan was changed differently on two phones. Both copies are kept: choose which to keep on Today.",
    "sync.copyPhone": "Changed differently on two phones: this is this phone's copy.",
    "sync.copyAccount": "Changed differently on two phones: this is the account's copy.",
    "sync.copyFacts": "{done} days done · finishing {date}.",
    "sync.keepThis": "Keep this copy",
    "sync.kept": "Kept. The other copy is under Settings → Stopped plans.",
    "stopped.title": "Stopped plans",
    "stopped.note": "Plans you stopped, or that another phone removed, are kept here so they can be brought back.",
    "stopped.facts": "{done} days done · stopped {date}",
    "stopped.bringBack": "Bring back",
    "stopped.broughtBack": "{name} is back",
    "backup.holds": "This backup holds {plans} plans with {days} days done, and {records} records of the days.",
    "backup.last": "Last backup: {date}",
    "backup.never": "No backup made yet on this phone.",
    "backup.undo": "Go back to how it was before loading the backup ({date})",
    "backup.undoAsk": "Go back to your plans as they were before loading the backup on {date}? The plans added from it are kept under Stopped plans.",
    "backup.undoYes": "Go back",
    "backup.undone": "Back to how it was before loading the backup",
    "backup.rejected": "This backup cannot be used: {n} parts of it are damaged. Nothing was changed.",
    "backup.isNew": "new",
    "backup.combined": "combined with yours, keeping every day done",
    "backup.bothKept": "both copies kept, to choose which",
    "backup.planFacts": "{done} of {total} days done",
    "backup.previewTitle": "This backup has {n} plans:",
    "backup.previewNote": "They are added to your plans. Nothing of yours is removed, and a copy of your plans as they are now is kept, to go back to.",
    "backup.add": "Add them",
    "backup.noRecovery": "Could not keep a copy of your plans first, so nothing was changed. The phone's storage may be full.",
    "sync.retry": "Retry",
    "sync.reload": "Reload",
    "sync.saveBackup": "Save a backup",
    "sync.notSaved": "Not saved to your account yet. Your learning is kept on this phone.",
    "sync.tooBig": "{n} plans are too big to save to the account. They are kept on this phone; save a backup to keep a copy.",
    "sync.updateApp": "The account did not accept this save: this version of the app is out of date. Reload to update; your learning is kept on this phone.",
    "signout.unsent": "{plans} plans and {days} days are not yet saved to your account.",
    "signout.sendFirst": "Save them to the account first",
    "signout.anyway": "Sign out anyway (they stay on this phone for this account)",
    "signout.stillUnsent": "Some changes still could not be saved. If you sign out, they stay on this phone and are saved when you sign in to this account again.",
    "signout.keptHere": "Signed out. Changes not yet saved stay on this phone for when you sign in again.",
    "delete.backupFirst": "Save a backup first if you may want your learning again. Once deleted it cannot be brought back.",
    "delete.signInAgainKept": "For your safety, sign in again, then delete. Changes not yet saved are kept on this phone.",
    "delete.partly": "Deleting stopped partway: {removed} of {total} items were removed, nothing more. Your plans are all still on this phone, and the account can still be used. Try again when online.",
    "delete.signInRemains": "Your plans and history were deleted, but the sign-in itself was not. Sign in again and delete once more to finish.",
    "gate.finishLink": "Finish signing in",
    "gate.sendAnother": "Send another link instead",
    "gate.typeEmailFirst": "Type your email address first",
    "save.account": "Saved to your account ({who})",
    "save.account.more": "Every change is saved to your account and is the same on your other phones.",
    "save.waiting": "Saved on this phone, waiting for a connection",
    "save.waiting.more": "Your learning is safe on this phone. It is sent to your account as soon as there is a connection.",
    "save.attention": "Needs attention: tap here",
    "save.attention.more": "Something could not be saved. Tap here to see what, or save a backup.",
    "save.phone": "Saved on this phone only",
    "save.phone.more": "This page cannot sign in, so your learning is kept on this phone only. Save a backup to keep a copy.",
    "welcome.ok": "Good",
    "welcome.missing": "Something is missing?",
    "welcome.text": "Your {n} plans and your learning up to {date} are here.",
    "welcome.none": "You are signed in. Plans you add are saved to your account.",
    "welcome.missingTitle": "If something is missing:",
    "welcome.tip1": "Check that this is the right account: {who}.",
    "welcome.tip2": "Learning marked on another phone while it was offline arrives when that phone is online again.",
    "welcome.tip3": "Plans that were stopped are under Settings → Stopped plans, and can be brought back.",
    "welcome.tip4": "If you saved a backup, you can load it: nothing you have now is removed.",
    "welcome.loadBackup": "Load a backup",
    "settings.signOutThisPhone": "Sign out of this phone",
    "settings.comingLater": "coming later",
    "lesson.markedWhat": "Marked done for {date}:",
    "kol.preparingN": "Preparing {n} of {all}…",
    "kol.loading": "Loading {name}…",
    "kol.tooBig": "These plans are too big to save to your account: {names}. They would be kept only on this phone. Choose a nearer finish date, or start them anyway?",
    "kol.createAnyway": "Start anyway",
    "add.tooBig": "This plan is too big to save to your account. It would be kept only on this phone (save backups). A nearer finish date makes it smaller.",
    "place.title": "Yom Tov",
    "place.ask": "Where do you keep Yom Tov?",
    "place.outside": "Outside Israel (two days)",
    "place.israel": "In Israel (one day)",
    "place.note": "Used for leaving out Yom Tov days and for reminders. You can change it in Settings.",
    "place.saved": "Saved",
    "privacy.savedTitle": "What is saved",
    "privacy.alsoSaved": "Also: the time of your daily reminder and your phone's time zone, how many minutes a day took if you enter it, and plans you share with a chavrusa.",
    "privacy.whoTitle": "Who can see it",
    "privacy.servicesTitle": "Outside services",
    "privacy.otherServices": "The page also loads its letters from Google Fonts and the sign-in library from jsDelivr. Sefaria is opened only when you tap \"Open on Sefaria\". There are no ads and no tracking.",
    "privacy.deleteTitle": "Deleting",
  },

  // Hebrew: the same keys (a key missing here shows in English)
  he: {
    "app.learningCalendar": "שעשועי",
    "app.notSavedOnThis": "לא נשמר בטלפון. ייתכן שהזיכרון מלא או חסום; השינויים האחרונים יאבדו כשהאפליקציה תיסגר.",
    "app.notSavedToAn": "עדיין לא נשמר בחשבון.",
    "app.signIn": "כניסה",
    "gate.signInToStart": "היכנסו כדי להתחיל. התוכניות וההתקדמות נשמרות בחשבון אחרי כל שינוי, והן זהות בכל טלפון ומחשב.",
    "gate.continueWithGoogle": "המשך עם Google",
    "gate.orGetASign": "או קבלו קישור כניסה במייל",
    "gate.youExampleCom": "you@example.com",
    "gate.emailMeASign": "שלחו לי קישור כניסה",
    "gate.whatWeKeep": "מה נשמר",
    "gate.yourEmailAddressAnd": "כתובת המייל ותוכניות הלימוד שלכם, רק כדי להציג אותן לכם. שום דבר אינו נמכר או משותף. ייתכן שנציג כמה אנשים לומדים כל ספר, לעולם לא מי הם. השם או הלימוד שלכם מוצגים לאחרים רק אם תפעילו זאת בהגדרות. אפשר למחוק את החשבון וכל מה שבו מההגדרות.",
    "gate.notNow": "לא עכשיו",
    "today.loading": "טוען…",
    "today.today": "היום",
    "today.addASefer": "הוספת ספר",
    "today.thisWeek": "השבוע",
    "today.startYourFirstSefer": "התחילו את הספר הראשון",
    "today.chooseASeferAnd": "בחרו ספר ואיך ללמוד אותו. בכל יום תראו מאיפה להתחיל ועד איפה ללמוד בספר שלכם.",
    "today.chooseASefer": "בחירת ספר",
    "library.learningNow": "לומדים עכשיו",
    "library.seforim": "ספרים",
    "library.nothingYet": "עדיין אין כלום",
    "library.seforimYouLearnWill": "הספרים שאתם לומדים יופיעו כאן עם ההתקדמות שלהם.",
    "plan.previousMonth": "החודש הקודם",
    "plan.nextMonth": "החודש הבא",
    "plan.done": "נלמד",
    "plan.toLearn": "ללמוד",
    "plan.off": "חופש",
    "plan.changeThePlan": "שינוי התוכנית",
    "plan.finishBy": "לסיים עד",
    "plan.daysOffFrom": "ימי חופש מ־",
    "plan.until": "עד",
    "plan.saveChanges": "שמירת השינויים",
    "plan.daysAlreadyDoneStay": "ימים שכבר נלמדו נשארים כמו שהם. מה שנשאר מתחלק מחדש.",
    "plan.daysOfThePlan": "ימי התוכנית",
    "plan.stopLearningThisSefer": "הפסקת הלימוד בספר הזה",
    "settings.settings": "הגדרות",
    "settings.account": "חשבון",
    "settings.notSignedInYour": "לא מחוברים. התוכניות נשמרות רק בטלפון הזה עד שתיכנסו.",
    "settings.signedInAs": "מחוברים בתור",
    "settings.yourPlansAreSaved": "התוכניות נשמרות בחשבון אחרי כל שינוי.",
    "settings.displayNameOptional": "שם לתצוגה (לא חובה)",
    "settings.howOtherLearnersWould": "איך לומדים אחרים יראו אתכם",
    "settings.letOtherLearnersSee": "לאפשר ללומדים אחרים לראות מה אני לומד",
    "settings.offUnlessYouTurn": "כבוי אלא אם תפעילו. כרגע לא מוצג לאף אחד דבר; זה בשביל אפשרויות שיבואו בהמשך.",
    "settings.signOut": "יציאה",
    "settings.deleteAccount": "מחיקת החשבון",
    "settings.privacy": "פרטיות",
    "settings.appearance": "מראה",
    "settings.theme": "ערכת צבע",
    "settings.automatic": "אוטומטי",
    "settings.light": "בהיר",
    "settings.dark": "כהה",
    "settings.style": "סגנון",
    "settings.solid": "אטום",
    "settings.glass": "זכוכית",
    "settings.color": "צבע",
    "settings.dailyReminder": "תזכורת יומית",
    "settings.aReminderFromYour": "תזכורת מיומן הטלפון בימי הלימוד. היא פותחת את האפליקציה, שמראה את המקום של היום.",
    "settings.time": "שעה",
    "settings.addToMyCalendar": "הוספה ליומן שלי",
    "settings.onIphoneAndIpad": "באייפון ובאייפד, הקישו „הוסף הכל” במסך הבא. באנדרואיד, פתחו את הקובץ באפליקציית היומן והקישו הוספה או ייבוא.",
    "settings.sectionNames": "שמות החלקים",
    "settings.hebrew": "עברית",
    "settings.english": "אנגלית",
    "settings.forSeforimDividedInto": "בספרים המחולקים לחלקים בעלי שם, כמו חובות הלבבות: <bdi lang=\"he\" dir=\"rtl\">שער ראשון - שער ייחוד ג</bdi> או First Treatise on Unity 3.",
    "settings.exportAndImport": "ייצוא וייבוא",
    "settings.aCopyOfYour": "עותק של התוכניות כקובץ, לשמירה או להעברה ידנית. לא צריך כשאתם מחוברים.",
    "settings.export": "ייצוא",
    "settings.importAFile": "ייבוא קובץ",
    "settings.ifNoFileWas": "אם לא נשמר קובץ, העתיקו את הטקסט הזה ושמרו אותו במקום בטוח, למשל במייל לעצמכם.",
    "settings.copyBackupText": "העתקת טקסט הגיבוי",
    "settings.loadABackupFrom": "טעינת גיבוי מטקסט מועתק",
    "settings.pasteTheBackupText": "הדביקו כאן את טקסט הגיבוי",
    "settings.loadThisBackup": "טעינת הגיבוי הזה",
    "settings.aboutAndSources": "אודות ומקורות",
    "privacy.ifYouSignIn": "אם תיכנסו לשעשועי, נשמור את כתובת המייל, שם לתצוגה אם תבחרו, ואת תוכניות הלימוד: אילו ספרים, ההגדרות, ורישום של כל יום שלמדתם, החסרתם או הזזתם.",
    "privacy.weKeepThemOnly": "אנחנו שומרים אותם רק כדי להציג לכם אותם, בכל טלפון או מחשב שבו תיכנסו. שום דבר אינו נמכר ושום דבר אינו משותף עם אף אחד.",
    "privacy.theyAreKeptWith": "הם נשמרים ב־Google Firebase, השירות שמפעיל את הכניסה והשמירה. כל חשבון יכול לגשת רק לתוכניות שלו.",
    "privacy.ifYouDoNot": "אם לא תיכנסו, שום דבר לא יוצא מהטלפון: התוכניות נשמרות רק בדפדפן הזה.",
    "privacy.weMayShowCounts": "ייתכן שנציג כמה אנשים לומדים כל ספר, לעולם לא מי הם.",
    "privacy.weOnlyShowYour": "הצגת השם שלכם או מה שאתם לומדים ללומדים אחרים תבוא בהמשך. היא תהיה רק אם תפעילו את „לאפשר ללומדים אחרים לראות מה אני לומד” בהגדרות, שכבוי אלא אם תפעילו.",
    "privacy.youCanDeleteYour": "אפשר למחוק את החשבון ואת כל התוכניות בכל עת: הגדרות, ואז מחיקת החשבון.",
    "about.about": "אודות שעשועי",
    "about.eachDayTheApp": "בכל יום שעשועי מראה מאיפה להתחיל ועד איפה ללמוד בספר המודפס שלכם, בשמות שבהם לוחות לימוד מודפסים קוראים לזה: העמוד, המשנה, הפסוק, ההלכה, הסעיף או הסימן, ומילים ספורות במקום שבו היום נגמר. גודל הימים נקבע לפי ההגדרות שלכם, כולל המפרשים שאתם לומדים יחד עם הטקסט.",
    "about.sources": "מקורות",
    "about.theSizesOfThe": "גודל הימים והמילים הספורות שמסמנות כל מקום לקוחים מטקסטים שפורסמו ב־<a href=\"https://www.sefaria.org\" target=\"_blank\" rel=\"noopener\">ספריא</a>, רק ממהדורות בנחלת הכלל, חוץ משתי אלה:",
    "about.theGemaraSText": "טקסט הגמרא: <b>תלמוד בבלי, ויקיטקסט</b> (Wikisource Talmud Bavli), ברישיון <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY-SA</a>, מתוך <a href=\"https://he.wikisource.org/wiki/%D7%AA%D7%9C%D7%9E%D7%95%D7%93_%D7%91%D7%91%D7%9C%D7%99\" target=\"_blank\" rel=\"noopener\">he.wikisource.org</a>. האפליקציה שומרת ממנו רק את המילים הראשונות של כל מקום.",
    "about.everyEditionAndIts": "כל מהדורה והרישיון שלה",
    "about.yerushalmi": "טקסט הירושלמי: <b>התלמוד הירושלמי, מהדורת היינריך גוגנהיימר</b> (ברלין, דה גרויטר, 1999-2015), ברישיון <a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY</a>, דרך <a href=\"https://www.sefaria.org/texts/Talmud/Yerushalmi\" target=\"_blank\" rel=\"noopener\">ספריא</a>. האפליקציה שומרת ממנו רק את המילים הראשונות של כל מקום, ומסמנת מקומות לפי פרק והלכה.",
    "add.cancel": "ביטול",
    "add.1Of3": "1 מתוך 3",
    "add.searchInEnglishOr": "חיפוש בעברית או באנגלית",
    "add.collections": "אוספים",
    "add.selectAllAvailable": "בחירת הכל",
    "add.clear": "ניקוי",
    "add.learnTogetherWith": "ללמוד יחד עם",
    "add.onlyPartOfThe": "רק חלק מהספר",
    "add.from": "מ־",
    "add.to": "עד",
    "add.setYourPace": "קצב הלימוד",
    "add.howMuch": "כמה",
    "add.dailyAmount": "כמות ליום",
    "add.timeADay": "זמן ביום",
    "add.finishOn": "לסיים ב־",
    "add.theSeferIsShared": "הספר מתחלק בשווה עד אז.",
    "add.eachDay": "בכל יום",
    "add.less": "פחות",
    "add.amud": "עמוד",
    "add.more": "יותר",
    "add.minutes": "דקות",
    "add.myPace": "הקצב שלי",
    "add.slower": "לאט",
    "add.average": "רגיל",
    "add.faster": "מהר",
    "add.daysILearn": "הימים שאני לומד",
    "add.lighterDay": "יום קל",
    "add.fri": "ו׳",
    "add.aShorterDayAbout": "יום קצר יותר, כשני שלישים מיום רגיל, למשל לפני שבת.",
    "add.startOn": "להתחיל ב־",
    "add.daysOff": "ימי חופש",
    "add.reasonOptional": "סיבה (לא חובה)",
    "add.vacationYomTov": "חופשה, יום טוב…",
    "add.addDaysOff": "הוספת ימי חופש",
    "add.yourPlan": "התוכנית שלכם",
    "add.next": "הבא",
    "add.startLearning": "להתחיל ללמוד",
    "app.screens": "מסכים",
    "missed.youMissedADay": "החסרתם יום",
    "missed.pushTheFinishDate": "לדחות את תאריך הסיום",
    "missed.spreadItOverThe": "לחלק על פני הימים הבאים",
    "missed.doubleUpOnThe": "להכפיל ביום הבא",
    "ask.yes": "כן",
    "today.addTime": "כמה דקות זה לקח? (לא חובה)",
    "today.timeSaved": "נשמר עם היום הזה",
    "reminder.title": "זמן ללמוד",
    "reminder.description": "פתחו את שעשועי כדי לראות את המקום של היום: {url}",
    "reminder.noDays": "לא נשארו ימים לתזכורת: רק שבת, יום טוב או ערבי שבת",
    "day.0": "א׳",
    "day.1": "ב׳",
    "day.2": "ג׳",
    "day.3": "ד׳",
    "day.4": "ה׳",
    "day.5": "ו׳",
    "day.6": "שבת",
    "unit.pasuk": "פסוק",
    "unit.pasuk.many": "פסוקים",
    "unit.mishnah": "משנה",
    "unit.mishnah.many": "משניות",
    "unit.amud": "עמוד",
    "unit.amud.many": "עמודים",
    "unit.halacha": "הלכה",
    "unit.halacha.many": "הלכות",
    "unit.seif": "סעיף",
    "unit.seif.many": "סעיפים",
    "unit.siman": "סימן",
    "unit.siman.many": "סימנים",
    "unit.section": "חלק",
    "unit.section.many": "חלקים",
    "name.someOf": "{col}: {n} מתוך {total}",
    "settings.anyColor": "כל צבע",
    "settings.colorN": "צבע {color}",
    "settings.namesHe": "שמות החלקים בעברית",
    "settings.namesEn": "שמות החלקים באנגלית",
    "route.fromWords": "{place}, מהמילים",
    "route.beginningOf": "תחילת {place}",
    "route.untilWords": "{place}, עד המילים",
    "route.endOf": "סוף {place}",
    "route.commSeifKatan": "{name} עד {siman}סעיף קטן {n}",
    "route.simanN": "סימן {n}, ",
    "route.commThrough": "{name} עד",
    "route.start": "התחלה",
    "route.stop": "סיום",
    "today.nothingNew": "אין לימוד חדש ביום הזה.",
    "today.allDoneToday": "הכל נלמד להיום. יישר כוח!",
    "today.allDone": "הכל נלמד. יישר כוח!",
    "today.stillToLearn": "נשארו {n} מתוך {all} ללמוד",
    "part.title": "איפה עצרתם?",
    "part.saved": "נשמר. בפעם הבאה ממשיכים מהמקום שבו עצרתם.",
    "save.notOnPhone": "סומן, אבל לא נשמר בטלפון",
    "missed.cantToday": "לא אוכל ללמוד היום",
    "missed.missedMany": "החסרתם {n} ימים",
    "missed.missedOne": "החסרתם יום",
    "missed.whatToday": "מה לעשות עם הלימוד של היום?",
    "missed.whatMissed": "מה לעשות עם הימים שהוחסרו?",
    "missed.done.push": "תאריך הסיום נדחה",
    "missed.done.spread": "חולק על פני הימים הבאים",
    "missed.done.double": "נוסף ליום הבא",
    "today.yasherKoach": "יישר כוח!",
    "load.aSefer": "ספר",
    "load.failed": "לא הצלחנו לטעון את הספר. ההתקדמות בו שמורה. בדקו את החיבור ונסו שוב.",
    "load.retry": "לנסות שוב",
    "load.still": "עדיין לא הצלחנו לטעון",
    "library.daysDone": "{n} מתוך {all} ימים",
    "library.behind": "{n} בפיגור",
    "plan.aboutMinutes": "כ־{n} דקות ביום",
    "plan.daysDone": "ימים נלמדו",
    "plan.onTrack": "בזמן",
    "plan.aheadBy": "{n} לפני הזמן",
    "plan.status": "מצב",
    "plan.finishingYear": "סיום {year}",
    "plan.finishing": "סיום",
    "plan.daysIn": "ימים ב{month}",
    "plan.noNewLearning": "אין לימוד חדש",
    "plan.unmark": "נלמד; הקישו לביטול",
    "plan.noDaysThisMonth": "אין בחודש הזה ימים של התוכנית.",
    "cal.done": "נלמד",
    "cal.notInPlan": "לא חלק מהתוכנית.",
    "cal.noNew": "אין לימוד חדש.",
    "plan.updated": "התוכנית עודכנה",
    "plan.stopAsk": "להפסיק ללמוד את {name}? ההתקדמות בו תימחק.",
    "plan.stopYes": "להפסיק",
    "day.short.0": "א",
    "day.short.1": "ב",
    "day.short.2": "ג",
    "day.short.3": "ד",
    "day.short.4": "ה",
    "day.short.5": "ו",
    "day.short.6": "ש",
    "add.stepOf": "{n} מתוך 3",
    "add.back": "חזרה",
    "collection.note.bavli": "רש״י ותוספות על סנהדרין אינם כלולים: אין להם מהדורה חופשית. לתמיד אין רש״י ותוספות בספריא.",
    "collection.note.yerushalmi": "לפי פרק והלכה, שזהים בכל ירושלמי מודפס (מספרי הדפים שונים בין הדפוסים). ממהדורת גוגנהיימר.",
    "collection.note.rambam": "לא כלולים, כי אין להם מהדורה חופשית: הלכות תפילין ומזוזה וספר תורה; ציצית; ברכות; מילה; וסדר התפילות.",
    "collection.note.shulchan-aruch": "משנה ברורה על אורח חיים סימנים א עד קפו משוערת: המהדורה החופשית חסרה אותם, ולכן אורכם משוער לפי מספר הסעיפים הקטנים.",
    "collection.note.halacha": "לא כלולים, כי אין להם מהדורה חופשית: ערוך השולחן אורח חיים, שולחן ערוך הרב.",
    "collection.note.mussar": "לא כלולים, כי אין להם מהדורה חופשית: תניא, חפץ חיים, שמירת הלשון, ארחות צדיקים, כוזרי, ספר החינוך.",
    "collection.note.midrash": "לא כלולים, כי אין להם מהדורה חופשית: זוהר, מכילתא.",
    "add.nothingMatches": "לא נמצא כלום.",
    "add.oneChosen": "נבחר {name}",
    "add.allChosen": "נבחרו כל {n}",
    "add.nChosen": "נבחרו {n}",
    "add.rangeHint": "כתבו כמו בספר, למשל {example}.",
    "add.endBeforeStart": "הסוף לפני ההתחלה.",
    "add.none": "אין",
    "add.chooseSome": "בחרו ספר אחד או יותר",
    "add.timeHint": "בקצב הזה כל הלימוד ייקח כ־{n} שעות.",
    "add.summary": "{n} ימים · סיום {date}",
    "add.days": "ימים",
    "add.aboutMinutes": "כ־{n} דקות ביום",
    "add.learnWith": "ללמוד עם",
    "add.textAlone": "הטקסט בלבד",
    "add.reviewDays": "ימים",
    "add.lighterX": "יום קל {day}",
    "add.starting": "התחלה",
    "add.firstDay": "היום הראשון, {date}",
    "add.chooseFirstOff": "בחרו את יום החופש הראשון",
    "add.remove": "הסרה",
    "add.skipYomTov": "בלי לימוד ביום טוב",
    "add.yomTovIsrael": "אין לימוד ביום טוב, יום אחד כמו בארץ ישראל (לפי אזור הזמן של הטלפון). חול המועד נשאר יום לימוד.",
    "add.yomTovOutside": "אין לימוד ביום טוב, שני ימים כמו בחוץ לארץ (לפי אזור הזמן של הטלפון). חול המועד נשאר יום לימוד.",
    "reminder.addFirst": "הוסיפו קודם ספר; התזכורת הולכת לפי התוכניות.",
    "reminder.days": "בימים {days}, ימי הלימוד, עד {date}, כשהספר האחרון מסתיים. אף פעם לא בשבת או ביום טוב, ובשעת ערב גם לא ביום שישי או בערב יום טוב. אם תוכנית משתנה, הוסיפו שוב.",
    "reminder.addSeferFirst": "הוסיפו קודם ספר",
    "backup.copied": "הגיבוי הועתק",
    "backup.selectAndCopy": "סמנו את הטקסט והעתיקו",
    "backup.notBackup": "זה לא גיבוי של שעשועי.",
    "backup.replaceAsk": "להחליף את {n} התוכניות שבטלפון ב־{m} שבגיבוי?",
    "backup.replace": "להחליף",
    "backup.partFailed": "חלק מהגיבוי לא נקרא. שום דבר לא השתנה.",
    "backup.loaded": "הגיבוי נטען",
    "load.catalogFailed": "לא הצלחנו לטעון את רשימת הספרים ({error}). בדקו את החיבור ונסו שוב.",
    "lesson.with": "עם {names}",
    "lesson.day": "יום",
    "lesson.finishing": "סיום {date}",
    "lesson.wholeSchedule": "כל התוכנית",
    "lesson.catchUp": "השלמה",
    "lesson.cantToday": "לא אוכל ללמוד היום",
    "lesson.siyum": "סיימתם את כל הספר. מזל טוב!",
    "lesson.undoLast": "ביטול היום האחרון",
    "lesson.fromDate": "מ־{date}",
    "lesson.markDone": "סימון שנלמד",
    "lesson.openSefaria": "פתיחה בספריא",
    "lesson.onlyPart": "למדתי רק חלק",
    "lesson.undo": "ביטול",
    "lesson.done": "נלמד",
    "lesson.doneToday": "נלמד להיום",
    "lesson.noLearning": "אין לימוד ביום הזה.",
    "lesson.next": "הבא, {date}:",
    "lesson.learnAhead": "ללמוד מראש: לסמן את {date}",
    "status.finished": "הסתיים",
    "status.behindOne": "יום אחד בפיגור",
    "status.behindMany": "{n} ימים בפיגור",
    "status.ahead": "{n} לפני הזמן",
    "status.onSchedule": "בזמן",
    "added": "{name} נוסף",
    "ask.save": "שמירה",
    "plan.paused": "מושהה",
    "plan.pausedSince": "מושהה מאז {date}. כשתמשיכו, תאריך הסיום יידחה במספר ימי ההשהיה.",
    "plan.resume": "להמשיך",
    "plan.resumed": "ממשיכים. מה שנשאר מתחלק מהיום.",
    "group.summary": "{n} ספרים יחד · סיום {date}",
    "group.pause": "השהיית הכל",
    "group.resume": "להמשיך הכל",
    "group.pausedToast": "מושהה. אין לימוד עד שתמשיכו.",
    "group.move": "הזזת תאריך הסיום",
    "group.moveTitle": "תאריך סיום חדש לכל הקבוצה",
    "group.moved": "כולם מסתיימים עכשיו ב־{date}",
    "group.changeOnToday": "הספר הזה חלק מקבוצה. השהו אותו או הזיזו את תאריך הסיום יחד עם האחרים, במסך היום.",
    "kol.title": "כל התורה בשנה",
    "kol.short": "ש״ס, משנה, רמב״ם, תנ״ך ושולחן ערוך, כולם מסתיימים באותו יום",
    "kol.intro": "תוכנית לכל אחד, כולן מתחילות ומסתיימות באותם תאריכים. אפשר להסיר כל אחד או להוסיף ספר אחר.",
    "kol.optional": "לא חובה",
    "kol.addOther": "הוספת ספר אחר",
    "kol.chooseOne": "בחרו לפחות אחד.",
    "kol.endAfterStart": "תאריך הסיום צריך להיות אחרי ההתחלה.",
    "kol.summary": "{n} תוכניות, מ־{start} עד {end}, כל אחת מתחלקת בשווה לפי גודלה.",
    "kol.create": "להתחיל כל התורה",
    "kol.making": "מכין…",
    "kol.made": "{n} תוכניות התחילו יחד",
    "cycles.title": "הצטרפות למחזור יומי",
    "cycles.short": "דף יומי, משנה יומית או רמב״ם יומי, ללמוד מה שכולם לומדים היום",
    "cycles.intro": "במחזור כולם לומדים אותו דבר באותו יום, ולכן הימים הולכים לפי המחזור ולא לפי ההגדרות שלכם.",
    "cycles.note.daf-yomi": "דף אחד ביום",
    "cycles.note.mishnah-yomit": "שתי משניות ביום",
    "cycles.note.rambam-3": "שלושה פרקים ביום",
    "cycles.note.rambam-1": "פרק אחד ביום",
    "cycles.today": "היום: {name}",
    "cycles.ends": "המחזור הזה מסתיים ב־{date}",
    "cycles.join": "הצטרפות",
    "cycles.joined": "הצטרפתם",
    "cycles.welcome": "הצטרפתם ל{name}",
    "cycle.pill": "מחזור יומי",
    "cycle.openPlace": "פתיחה בספריא",
    "cycle.placeOnly": "לא נמצא בטקסטים של האפליקציה: למדו אותו מהספר שלכם.",
    "cycle.noChanges": "מחזור יומי הולך לפי התאריכים של המחזור: כולם לומדים אותו דבר באותו יום, ולכן אי אפשר לשנות את הימים.",
    "review.pill": "חזרה",
    "review.switch": "זו חזרה",
    "review.note": "מסומן כחזרה, בקצב משלה. הלימוד הראשון נשאר כמו שהיה.",
    "review.start": "חזרה על מה שלמדתי",
    "review.nothingYet": "סמנו קודם כמה ימים שנלמדו",
    "dedication.title": "הקדשה (לא חובה)",
    "dedication.none": "אין",
    "dedication.iluiNishmas": "לעילוי נשמת",
    "dedication.refuah": "לרפואה שלמה",
    "dedication.namePlaceholder": "שם, למשל פלוני בן פלוני",
    "dedication.save": "שמירת ההקדשה",
    "dedication.saved": "ההקדשה נשמרה",
    "dedication.lineIlui": "לעילוי נשמת",
    "dedication.lineRefuah": "לרפואה שלמה",
    "suggest.title": "לקראת {name}",
    "suggest.sub": "לסיים עד ערב יום טוב, {date}",
    "suggest.start": "להתחיל",
    "suggest.hide": "לא השנה",
    "suggest.noRange": "החלק הזה לא נמצא באפליקציה",
    "account.framed": "הכניסה עובדת באתר, sefer-calendar.web.app, ולא בתצוגה המקדימה הזו. התוכניות כאן נשמרות רק בטלפון הזה.",
    "account.offline": "הכניסה צריכה חיבור. בינתיים התוכניות נשמרות בטלפון, ויעברו לחשבון כשתיכנסו.",
    "account.linkSent": "שלחנו קישור כניסה אל {email}. פתחו אותו בטלפון הזה כדי להיכנס.",
    "account.typeEmail": "כדי לסיים את הכניסה בטלפון הזה, הקלידו את כתובת המייל שאליה נשלח הקישור, ואז הקישו „לסיים את הכניסה”.",
    "account.error.invalid-email": "כתובת המייל לא נראית תקינה.",
    "account.error.network-request-failed": "אין חיבור. נסו שוב כשהטלפון מחובר.",
    "account.error.invalid-action-code": "קישור הכניסה כבר שומש או ישן מדי (קישור עובד פעם אחת, כשעה). הקלידו את המייל כדי לקבל חדש.",
    "account.error.expired-action-code": "קישור הכניסה ישן מדי (קישור עובד כשעה). הקלידו את המייל כדי לקבל חדש.",
    "account.error.unauthorized-domain": "הכניסה עדיין לא הוגדרה לכתובת האתר הזו.",
    "account.error.operation-not-allowed": "דרך הכניסה הזו עדיין לא הופעלה.",
    "account.error.other": "לא הצלחנו להיכנס ({code}).",
    "account.yours": "החשבון שלכם",
    "account.unreachable": "לא הצלחנו להגיע לחשבון. השינויים נשמרים בטלפון וישלחו אחר כך.",
    "account.uploadedMany": "{n} תוכניות מהטלפון נשמרו בחשבון",
    "account.uploadedOne": "תוכנית אחת מהטלפון נשמרה בחשבון",
    "account.saveFailed": "לא הצלחנו לשמור בחשבון. השינויים נשמרים בטלפון וישלחו אחר כך.",
    "account.nameSaved": "השם נשמר",
    "account.signedOut": "יצאתם. התוכניות נשארות בחשבון.",
    "account.deleteAsk": "למחוק את החשבון ואת כל התוכניות? אי אפשר לבטל את זה.",
    "account.deleteYes": "למחוק הכל",
    "account.signInAgain": "לביטחונכם, היכנסו שוב ואז מחקו.",
    "account.deleted": "החשבון והתוכניות נמחקו.",
    "account.deleteFailed": "לא הצלחנו למחוק את החשבון. נסו שוב כשיש חיבור.",
    "engine.siman": "סימן {n}",
    "engine.time.2": " (בפעם השנייה)",
    "engine.time.3": " (בפעם השלישית)",
    "engine.time.4": " (בפעם הרביעית)",
    "engine.time.5": " (בפעם החמישית)",
    "engine.time.6": " (בפעם השישית)",
    "engine.time.7": " (בפעם השביעית)",
    "engine.time.8": " (בפעם השמינית)",
    "engine.time.9": " (בפעם התשיעית)",
    "engine.time.10": " (בפעם העשירית)",
    "engine.time.n": " (בפעם ה־{n})",
    "engine.simanComma": "סימן {n}, ",
    "engine.seifKatan": "{name} עד {siman}סעיף קטן {n}",
    "engine.commThrough": "{name} עד „{words}”",
    "engine.commOn": "{name} על {place}",
    "engine.fromWords": ", מהמילים „{words}”{time}",
    "engine.untilWords": ", עד המילים „{words}”{time}",
    "engine.toTheEndComma": ", עד סוף {place}",
    "engine.aToB": "{a} עד {b}",
    "engine.simanim": "סימנים {a}–{b}",
    "engine.theEndOf": "סוף {place}",
    "engine.hasNo": "ב{name} אין {place}",
    "engine.whichSefer": "כתבו איזה ספר, למשל {example}",
    "engine.noDaysSet": "לא נבחרו ימי לימוד",
    "engine.noDaysBefore": "אין ימי לימוד לפני תאריך הסיום",
    "engine.tooSmall": "הכמות היומית קטנה מדי",
    "engine.outside": "ההתחלה והסוף מחוץ לספר",
    "engine.oneDay": "בחרו לפחות יום לימוד אחד",
    "engine.endBeforeStart": "תאריך הסיום לפני ההתחלה",
    "engine.chooseHow": "בחרו תאריך סיום, כמות ליום או כמה דקות יש לכם בכל יום",
    "engine.insideDay": "בחרו מקום בתוך היום הזה",
    "export.button": "הוספת כל הימים ליומן שלי",
    "export.note": "כל יום לימוד כאירוע של יום שלם עם המקום והקישור לספריא. אחרי שינוי, הוסיפו שוב: הימים מתעדכנים ולא מוכפלים.",
    "export.summary": "{name}: יום {n} מתוך {all}",
    "print.button": "הדפסת השבוע",
    "print.title": "לימוד ל־{from} – {to}",
    "print.nothing": "אין לימוד",
    "print.foot": "מתוך שעשועי, sefer-calendar.web.app. סמנו כל תיבה כשסיימתם.",
    "share.button": "ללמוד עם חברותא",
    "share.again": "לשלוח שוב את הקישור לחברותא",
    "share.howTo": "שלחו את הקישור. החברותא פותח אותו, נכנס, ומקבל אותה תוכנית. כל אחד רואה עד איפה השני הגיע.",
    "share.send": "שליחה",
    "share.copy": "העתקת הקישור",
    "share.copied": "הקישור הועתק",
    "share.message": "בוא נלמד {name} יחד. פתח את הקישור כדי להצטרף:",
    "share.signInFirst": "היכנסו קודם, כדי שאפשר יהיה לשתף את התוכנית",
    "share.someone": "חברותא",
    "share.notFound": "לא הצלחנו לפתוח את קישור החברותא. בקשו קישור חדש.",
    "share.joinAsk": "ללמוד {name} יחד עם {who}? תקבלו אותה תוכנית, וכל אחד יראה עד איפה השני הגיע.",
    "share.join": "ללמוד יחד",
    "share.joined": "אתם לומדים יחד עם {who}",
    "share.waiting": "שותף עם חברותא: מחכים שיצטרף",
    "share.progress": "{done} מתוך {total} ימים",
    "share.doneToday": "למד היום",
    "share.lastDone": "למד לאחרונה {date}",
    "privacy.sharing": "אם תשתפו תוכנית עם חברותא, מי שתשלחו לו את הקישור יוכל לראות את לוח הזמנים של התוכנית, את השם שלכם לתצוגה, וכמה ימים למדתם בה. שום דבר אחר אינו משותף.",
    "settings.language": "שפה",
    "settings.languageNote": "השפה של המסכים. שמות הספרים מופיעים בעברית בכל מקרה.",
    "settings.langEnglish": "English",
    "settings.langHebrew": "עברית",
    "sync.conflict": "תוכנית שונתה באופן שונה בשני טלפונים. שני העותקים נשמרו: בחרו במסך היום איזה לשמור.",
    "sync.copyPhone": "שונה באופן שונה בשני טלפונים: זה העותק של הטלפון הזה.",
    "sync.copyAccount": "שונה באופן שונה בשני טלפונים: זה העותק שבחשבון.",
    "sync.copyFacts": "{done} ימים נלמדו · סיום {date}.",
    "sync.keepThis": "לשמור את העותק הזה",
    "sync.kept": "נשמר. העותק השני נמצא בהגדרות ← תוכניות שהופסקו.",
    "stopped.title": "תוכניות שהופסקו",
    "stopped.note": "תוכניות שהפסקתם, או שטלפון אחר הסיר, נשמרות כאן כדי שאפשר יהיה להחזיר אותן.",
    "stopped.facts": "{done} ימים נלמדו · הופסק {date}",
    "stopped.bringBack": "להחזיר",
    "stopped.broughtBack": "{name} חזר",
    "backup.holds": "בגיבוי הזה {plans} תוכניות עם {days} ימים שנלמדו, ו־{records} רישומים של הימים.",
    "backup.last": "גיבוי אחרון: {date}",
    "backup.never": "עדיין לא נעשה גיבוי בטלפון הזה.",
    "backup.undo": "לחזור למצב שלפני טעינת הגיבוי ({date})",
    "backup.undoAsk": "לחזור לתוכניות כפי שהיו לפני טעינת הגיבוי ב־{date}? התוכניות שנוספו ממנו יישמרו בתוכניות שהופסקו.",
    "backup.undoYes": "לחזור",
    "backup.undone": "חזרנו למצב שלפני טעינת הגיבוי",
    "backup.rejected": "אי אפשר להשתמש בגיבוי הזה: {n} חלקים בו פגומים. שום דבר לא השתנה.",
    "backup.isNew": "חדשה",
    "backup.combined": "מצורפת לשלכם, וכל יום שנלמד נשמר",
    "backup.bothKept": "שני העותקים נשמרים, כדי לבחור",
    "backup.planFacts": "{done} מתוך {total} ימים נלמדו",
    "backup.previewTitle": "בגיבוי הזה {n} תוכניות:",
    "backup.previewNote": "הן נוספות לתוכניות שלכם. שום דבר שלכם לא נמחק, ונשמר עותק של התוכניות כפי שהן עכשיו, כדי לחזור אליו.",
    "backup.add": "להוסיף אותן",
    "backup.noRecovery": "לא הצלחנו לשמור קודם עותק של התוכניות, ולכן שום דבר לא השתנה. ייתכן שזיכרון הטלפון מלא.",
    "sync.retry": "לנסות שוב",
    "sync.reload": "לטעון מחדש",
    "sync.saveBackup": "שמירת גיבוי",
    "sync.notSaved": "עדיין לא נשמר בחשבון. הלימוד שמור בטלפון הזה.",
    "sync.tooBig": "{n} תוכניות גדולות מדי לשמירה בחשבון. הן שמורות בטלפון הזה; שמרו גיבוי כדי שיהיה עותק.",
    "sync.updateApp": "החשבון לא קיבל את השמירה: הגרסה הזו של האפליקציה ישנה. טענו מחדש כדי לעדכן; הלימוד שמור בטלפון הזה.",
    "signout.unsent": "{plans} תוכניות ו־{days} ימים עדיין לא נשמרו בחשבון.",
    "signout.sendFirst": "לשמור אותם קודם בחשבון",
    "signout.anyway": "לצאת בכל זאת (הם נשארים בטלפון הזה לחשבון הזה)",
    "signout.stillUnsent": "חלק מהשינויים עדיין לא נשמרו. אם תצאו, הם יישארו בטלפון הזה ויישמרו כשתיכנסו שוב לחשבון הזה.",
    "signout.keptHere": "יצאתם. שינויים שעוד לא נשמרו נשארים בטלפון הזה לכניסה הבאה.",
    "delete.backupFirst": "שמרו קודם גיבוי אם אולי תרצו את הלימוד שוב. אחרי המחיקה אי אפשר להחזיר.",
    "delete.signInAgainKept": "לביטחונכם, היכנסו שוב ואז מחקו. שינויים שעוד לא נשמרו שמורים בטלפון הזה.",
    "delete.partly": "המחיקה נעצרה באמצע: {removed} מתוך {total} פריטים נמחקו, ולא יותר. כל התוכניות עדיין בטלפון הזה, ואפשר להמשיך להשתמש בחשבון. נסו שוב כשיש חיבור.",
    "delete.signInRemains": "התוכניות וההיסטוריה נמחקו, אבל הכניסה עצמה לא. היכנסו שוב ומחקו שוב כדי לסיים.",
    "gate.finishLink": "לסיים את הכניסה",
    "gate.sendAnother": "לשלוח קישור אחר במקום",
    "gate.typeEmailFirst": "הקלידו קודם את כתובת המייל",
    "save.account": "נשמר בחשבון ({who})",
    "save.account.more": "כל שינוי נשמר בחשבון וזהה בטלפונים האחרים שלכם.",
    "save.waiting": "נשמר בטלפון, מחכה לחיבור",
    "save.waiting.more": "הלימוד שמור בטלפון הזה. הוא יישלח לחשבון ברגע שיהיה חיבור.",
    "save.attention": "צריך תשומת לב: הקישו כאן",
    "save.attention.more": "משהו לא נשמר. הקישו כאן כדי לראות מה, או שמרו גיבוי.",
    "save.phone": "נשמר רק בטלפון הזה",
    "save.phone.more": "מהדף הזה אי אפשר להיכנס, ולכן הלימוד נשמר רק בטלפון הזה. שמרו גיבוי כדי שיהיה עותק.",
    "welcome.ok": "טוב",
    "welcome.missing": "משהו חסר?",
    "welcome.text": "{n} התוכניות שלכם והלימוד עד {date} נמצאים כאן.",
    "welcome.none": "נכנסתם. תוכניות שתוסיפו יישמרו בחשבון.",
    "welcome.missingTitle": "אם משהו חסר:",
    "welcome.tip1": "בדקו שזה החשבון הנכון: {who}.",
    "welcome.tip2": "לימוד שסומן בטלפון אחר בזמן שהיה בלי חיבור יגיע כשהטלפון ההוא יתחבר שוב.",
    "welcome.tip3": "תוכניות שהופסקו נמצאות בהגדרות ← תוכניות שהופסקו, ואפשר להחזיר אותן.",
    "welcome.tip4": "אם שמרתם גיבוי, אפשר לטעון אותו: שום דבר ממה שיש לכם עכשיו לא נמחק.",
    "welcome.loadBackup": "טעינת גיבוי",
    "settings.signOutThisPhone": "יציאה מהטלפון הזה",
    "settings.comingLater": "בקרוב",
    "lesson.markedWhat": "סומן שנלמד ל־{date}:",
    "kol.preparingN": "מכין {n} מתוך {all}…",
    "kol.loading": "טוען את {name}…",
    "kol.tooBig": "התוכניות האלה גדולות מדי לשמירה בחשבון: {names}. הן יישמרו רק בטלפון הזה. לבחור תאריך סיום קרוב יותר, או להתחיל בכל זאת?",
    "kol.createAnyway": "להתחיל בכל זאת",
    "add.tooBig": "התוכנית הזו גדולה מדי לשמירה בחשבון. היא תישמר רק בטלפון הזה (שמרו גיבויים). תאריך סיום קרוב יותר יקטין אותה.",
    "place.title": "יום טוב",
    "place.ask": "איפה אתם שומרים יום טוב?",
    "place.outside": "בחוץ לארץ (שני ימים)",
    "place.israel": "בארץ ישראל (יום אחד)",
    "place.note": "משמש להשמטת ימי יום טוב ולתזכורות. אפשר לשנות בהגדרות.",
    "place.saved": "נשמר",
    "privacy.savedTitle": "מה נשמר",
    "privacy.alsoSaved": "וגם: שעת התזכורת היומית ואזור הזמן של הטלפון, כמה דקות לקח יום אם הזנתם, ותוכניות ששיתפתם עם חברותא.",
    "privacy.whoTitle": "מי יכול לראות",
    "privacy.servicesTitle": "שירותים חיצוניים",
    "privacy.otherServices": "הדף טוען גם את הגופנים מ־Google Fonts ואת ספריית הכניסה מ־jsDelivr. ספריא נפתחת רק כשמקישים „פתיחה בספריא”. אין פרסומות ואין מעקב.",
    "privacy.deleteTitle": "מחיקה",
  },
};

  let lang = "en";
  try { if (STRINGS[localStorage.getItem("learning-calendar-language")]) lang = localStorage.getItem("learning-calendar-language"); } catch (e) { /* English */ }

  function tr(key, vars) {
    let s = (STRINGS[lang] && STRINGS[lang][key]) ?? STRINGS.en[key];
    if (s === undefined) { if (global.console) console.warn("No text for", key); s = key; }
    return vars ? s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] !== undefined ? vars[k] : m)) : s;
  }
  function applyStrings(root) {
    root = root || document;
    root.querySelectorAll("[data-t]").forEach((el) => { el.textContent = tr(el.dataset.t); });
    root.querySelectorAll("[data-t-html]").forEach((el) => { el.innerHTML = tr(el.dataset.tHtml); });
    for (const a of ["placeholder", "aria-label", "title", "alt"]) {
      root.querySelectorAll(`[data-t-${a}]`).forEach((el) => { el.setAttribute(a, tr(el.getAttribute(`data-t-${a}`))); });
    }
  }
  // Every screen is built to run right-to-left too: the page's direction follows the language.
  const RTL = ["he", "yi"];
  function applyLanguage() {
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL.includes(lang) ? "rtl" : "ltr";
    applyStrings();
  }

  global.STRINGS = STRINGS;
  global.tr = tr;
  global.LearnText = { tr, applyStrings, language: () => lang, locale: () => (lang === "he" ? "he-IL" : "en-US") };
  if (typeof document !== "undefined" && document.querySelector) applyLanguage();
  if (typeof module !== "undefined" && module.exports) module.exports = global.LearnText;
})(typeof window !== "undefined" ? window : globalThis);
