/*
 * Every word the app shows, in one place.
 *
 * STRINGS.en holds the English; a Hebrew list (STRINGS.he) can be added later
 * with the same keys, and any key missing from it falls back to English.
 * In the page, an element with data-t="key" gets that text, data-t-html="key"
 * gets it as HTML (for a link or bold word inside), and data-t-placeholder,
 * data-t-aria-label and data-t-title fill those attributes. In code: tr("key")
 * or tr("key", { n: 3 }) for "{n}" inside the text.
 */
(function (global) {
  "use strict";
  const STRINGS = { en: {
    // app
    "app.learningCalendar": "Learning Calendar",
    "app.notSavedOnThis": "Not saved on this phone. The phone's storage may be full or blocked; your latest changes will be lost when the app closes.",
    "app.notSavedToAn": "Not saved to an account yet.",
    "app.signIn": "Sign in",

    // gate
    "gate.signInToStart": "Sign in to start. Your plans and progress are saved to your account after every change, and are the same on every phone and computer.",
    "gate.continueWithGoogle": "Continue with Google",
    "gate.orGetASign": "Or get a sign-in link by email",
    "gate.youExampleCom": "you@example.com",
    "gate.emailMeASign": "Email me a sign-in link",
    "gate.whatWeKeep": "What we keep",
    "gate.yourEmailAddressAnd": "Your email address and your learning plans, only to show them to you. Nothing is sold or shared. We may show counts of how many people learn each sefer, never who they are. Your name or learning is shown to others only if you turn that on in Settings. You can delete your account and everything in it from Settings.",
    "gate.notNow": "Not now",

    // today
    "today.loading": "Loading…",
    "today.today": "Today",
    "today.addASefer": "Add a sefer",
    "today.thisWeek": "This week",
    "today.startYourFirstSefer": "Start your first sefer",
    "today.chooseASeferAnd": "Choose a sefer and how you want to learn it. Each day you get where to start and where to stop in your own sefer.",
    "today.chooseASefer": "Choose a sefer",

    // library
    "library.learningNow": "Learning now",
    "library.seforim": "Seforim",
    "library.nothingYet": "Nothing yet",
    "library.seforimYouLearnWill": "Seforim you learn will be listed here with their progress.",

    // plan
    "plan.previousMonth": "Previous month",
    "plan.nextMonth": "Next month",
    "plan.done": "Done",
    "plan.toLearn": "To learn",
    "plan.off": "Off",
    "plan.changeThePlan": "Change the plan",
    "plan.finishBy": "Finish by",
    "plan.daysOffFrom": "Days off from",
    "plan.until": "until",
    "plan.saveChanges": "Save changes",
    "plan.daysAlreadyDoneStay": "Days already done stay as they are. What is left is shared out again.",
    "plan.daysOfThePlan": "Days of the plan",
    "plan.stopLearningThisSefer": "Stop learning this sefer",

    // settings
    "settings.settings": "Settings",
    "settings.account": "Account",
    "settings.notSignedInYour": "Not signed in. Your plans are kept on this phone only until you sign in.",
    "settings.signedInAs": "Signed in as",
    "settings.yourPlansAreSaved": "Your plans are saved to your account after every change.",
    "settings.displayNameOptional": "Display name (optional)",
    "settings.howOtherLearnersWould": "How other learners would see you",
    "settings.letOtherLearnersSee": "Let other learners see what I'm learning",
    "settings.offUnlessYouTurn": "Off unless you turn it on. Nothing is shown to anyone yet; this is for features coming later.",
    "settings.signOut": "Sign out",
    "settings.deleteAccount": "Delete account",
    "settings.privacy": "Privacy",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.automatic": "Automatic",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.style": "Style",
    "settings.solid": "Solid",
    "settings.glass": "Glass",
    "settings.color": "Color",
    "settings.dailyReminder": "Daily reminder",
    "settings.aReminderFromYour": "A reminder from your phone's own calendar on your learning days. It opens the app, which shows the day's place.",
    "settings.time": "Time",
    "settings.addToMyCalendar": "Add to my calendar",
    "settings.onIphoneAndIpad": "On iPhone and iPad, tap “Add All” on the next screen. On Android, open the file with your calendar app and tap Add or Import.",
    "settings.sectionNames": "Section names",
    "settings.hebrew": "Hebrew",
    "settings.english": "English",
    "settings.forSeforimDividedInto": "For seforim divided into named sections, like Chovos HaLevavos: <bdi lang=\"he\" dir=\"rtl\">שער ראשון - שער ייחוד ג</bdi> or First Treatise on Unity 3.",
    "settings.exportAndImport": "Export and import",
    "settings.aCopyOfYour": "A copy of your plans as a file, to keep or to move by hand. Not needed when you are signed in.",
    "settings.export": "Export",
    "settings.importAFile": "Import a file",
    "settings.ifNoFileWas": "If no file was saved, copy this text and keep it somewhere safe, for example in an email to yourself.",
    "settings.copyBackupText": "Copy backup text",
    "settings.loadABackupFrom": "Load a backup from copied text",
    "settings.pasteTheBackupText": "Paste the backup text here",
    "settings.loadThisBackup": "Load this backup",
    "settings.aboutAndSources": "About and sources",

    // privacy
    "privacy.ifYouSignIn": "If you sign in, we store your email address, a display name if you choose one, and your learning plans: which seforim, your settings, and a record of each day you learned, missed or moved.",
    "privacy.weKeepThemOnly": "We keep them only to show them back to you, on any phone or computer where you sign in. Nothing is sold, and nothing is shared with anyone.",
    "privacy.theyAreKeptWith": "They are kept with Google Firebase, the service that runs the sign-in and the saving. Each account can reach only its own plans.",
    "privacy.ifYouDoNot": "If you do not sign in, nothing leaves your phone: your plans are kept in this browser only.",
    "privacy.weMayShowCounts": "We may show counts of how many people learn each sefer, never who they are.",
    "privacy.weOnlyShowYour": "We only show your name or what you are learning to other learners if you turn on \"Let other learners see what I'm learning\" in Settings. It is off unless you turn it on.",
    "privacy.youCanDeleteYour": "You can delete your account and all your plans at any time: Settings, then Delete account.",

    // about
    "about.about": "About",
    "about.eachDayTheApp": "Each day the app shows where to start and where to stop in your own printed sefer, named the way printed learning calendars name it: the amud, mishnah, pasuk, halacha, se'if or siman, and the first few words where the day stops. Days are sized by your settings, counting the commentaries you learn together with the text.",
    "about.sources": "Sources",
    "about.theSizesOfThe": "The sizes of the days and the few words that name each place come from texts published by <a href=\"https://www.sefaria.org\" target=\"_blank\" rel=\"noopener\">Sefaria</a>, using only Public Domain editions, except these two:",
    "about.theGemaraSText": "The Gemara's text: <b>Wikisource Talmud Bavli</b> (<bdi lang=\"he\" dir=\"rtl\">תלמוד בבלי, ויקיטקסט</bdi>), licensed <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY-SA</a>, from <a href=\"https://he.wikisource.org/wiki/%D7%AA%D7%9C%D7%9E%D7%95%D7%93_%D7%91%D7%91%D7%9C%D7%99\" target=\"_blank\" rel=\"noopener\">he.wikisource.org</a>. The app keeps only the first few words of each place in it.",
    "about.everyEditionAndIts": "Every edition and its license",

    // add
    "add.cancel": "Cancel",
    "add.1Of3": "1 of 3",
    "add.searchInEnglishOr": "Search in English or Hebrew",
    "add.collections": "Collections",
    "add.selectAllAvailable": "Select all available",
    "add.clear": "Clear",
    "add.learnTogetherWith": "Learn together with",
    "add.onlyPartOfThe": "Only part of the sefer",
    "add.from": "From",
    "add.to": "To",
    "add.setYourPace": "Set your pace",
    "add.howMuch": "How much",
    "add.dailyAmount": "Daily amount",
    "add.timeADay": "Time a day",
    "add.finishOn": "Finish on",
    "add.theSeferIsShared": "The sefer is shared out evenly until then.",
    "add.eachDay": "Each day",
    "add.less": "Less",
    "add.amud": "amud",
    "add.more": "More",
    "add.minutes": "minutes",
    "add.myPace": "My pace",
    "add.slower": "Slower",
    "add.average": "Average",
    "add.faster": "Faster",
    "add.daysILearn": "Days I learn",
    "add.lighterDay": "Lighter day",
    "add.fri": "Fri",
    "add.aShorterDayAbout": "A shorter day, about two-thirds of a usual day, for example before Shabbos.",
    "add.startOn": "Start on",
    "add.daysOff": "Days off",
    "add.reasonOptional": "Reason (optional)",
    "add.vacationYomTov": "Vacation, Yom Tov…",
    "add.addDaysOff": "Add days off",
    "add.yourPlan": "Your plan",
    "add.next": "Next",
    "add.startLearning": "Start learning",

    // app
    "app.screens": "Screens",

    // missed
    "missed.youMissedADay": "You missed a day",
    "missed.pushTheFinishDate": "Push the finish date later",
    "missed.spreadItOverThe": "Spread it over the coming days",
    "missed.doubleUpOnThe": "Double up on the next day",

    // ask
    "ask.yes": "Yes",

    // added in code (app.js, accounts.js)
    "today.addTime": "How many minutes did it take? (optional)",
    "today.timeSaved": "Saved with this day",
    "reminder.title": "Time to learn",
    "reminder.description": "Open the Learning Calendar to see today's place: {url}",
    "reminder.noDays": "No days left for a reminder: only Shabbos, Yom Tov or Friday evenings",
    "day.0": "Sun",
    "day.1": "Mon",
    "day.2": "Tue",
    "day.3": "Wed",
    "day.4": "Thu",
    "day.5": "Fri",
    "day.6": "Shabbos",
    "unit.pasuk": "pasuk",
    "unit.pasuk.many": "pesukim",
    "unit.mishnah": "mishnah",
    "unit.mishnah.many": "mishnayos",
    "unit.amud": "amud",
    "unit.amud.many": "amudim",
    "unit.halacha": "halacha",
    "unit.halacha.many": "halachos",
    "unit.seif": "se'if",
    "unit.seif.many": "se'ifim",
    "unit.siman": "siman",
    "unit.siman.many": "simanim",
    "unit.section": "section",
    "unit.section.many": "sections",
    "name.someOf": "{col}: {n} of {total}",
    "settings.anyColor": "Any color",
    "settings.colorN": "Color {color}",
    "settings.namesHe": "Section names in Hebrew",
    "settings.namesEn": "Section names in English",
    "route.fromWords": "{place}, from the words",
    "route.beginningOf": "the beginning of {place}",
    "route.untilWords": "{place}, until the words",
    "route.endOf": "the end of {place}",
    "route.commSeifKatan": "{name} through {siman}se'if katan {n}",
    "route.simanN": "siman {n}, ",
    "route.commThrough": "{name} through",
    "route.start": "Start",
    "route.stop": "Stop",
    "today.nothingNew": "Nothing new to learn on this day.",
    "today.allDoneToday": "All done for today. Yasher koach!",
    "today.allDone": "All done. Yasher koach!",
    "today.stillToLearn": "{n} of {all} still to learn",
    "part.title": "Where did you stop?",
    "part.saved": "Saved. Next time starts where you stopped.",
    "save.notOnPhone": "Marked, but not saved on this phone",
    "missed.cantToday": "Can't learn today",
    "missed.missedMany": "You missed {n} days",
    "missed.missedOne": "You missed a day",
    "missed.whatToday": "What should happen to today's portion?",
    "missed.whatMissed": "What should happen to the portions you missed?",
    "missed.done.push": "The finish date moved later",
    "missed.done.spread": "Spread over the coming days",
    "missed.done.double": "Added to the next day",
    "today.yasherKoach": "Yasher koach!",
    "load.aSefer": "A sefer",
    "load.failed": "Could not load this sefer. Your progress in it is kept. Check the connection and try again.",
    "load.retry": "Retry",
    "load.still": "Still could not load it",
    "library.daysDone": "{n} of {all} days",
    "library.behind": "{n} behind",
    "plan.aboutMinutes": "about {n} minutes a day",
    "plan.daysDone": "days done",
    "plan.onTrack": "On track",
    "plan.aheadBy": "ahead by {n}",
    "plan.status": "status",
    "plan.finishingYear": "finishing {year}",
    "plan.finishing": "finishing",
    "plan.daysIn": "Days in {month}",
    "plan.noNewLearning": "No new learning",
    "plan.unmark": "Done; tap to unmark",
    "plan.noDaysThisMonth": "No days of this plan in this month.",
    "cal.done": "done",
    "cal.notInPlan": "Not part of the plan.",
    "cal.noNew": "No new learning.",
    "plan.updated": "Plan updated",
    "plan.stopAsk": "Stop learning {name}? Its progress will be removed.",
    "plan.stopYes": "Stop learning it",
    "day.short.0": "Su",
    "day.short.1": "Mo",
    "day.short.2": "Tu",
    "day.short.3": "We",
    "day.short.4": "Th",
    "day.short.5": "Fr",
    "day.short.6": "Sh",
    "add.stepOf": "{n} of 3",
    "add.back": "Back",
    "collection.note.bavli": "Rashi and Tosafot on Sanhedrin are not included: there is no free edition. Tamid has no Rashi or Tosafot on Sefaria.",
    "collection.note.yerushalmi": "Named by perek and halacha, which match every printed Yerushalmi (daf numbers differ between printings). From Guggenheimer's edition.",
    "collection.note.rambam": "Not included, because there is no free edition: Hilchos Tefillin, Mezuzah and Sefer Torah; Tzitzis; Berachos; Milah; and the Order of Prayers.",
    "collection.note.shulchan-aruch": "Mishnah Berurah on Orach Chaim simanim 1 to 186 is estimated: the free edition does not have them, so their length is estimated from the number of se'ifim katanim.",
    "collection.note.halacha": "Not included, because there is no free edition: Aruch HaShulchan Orach Chaim, Shulchan Aruch HaRav.",
    "collection.note.mussar": "Not included, because there is no free edition: Tanya, Chofetz Chaim, Shemiras HaLashon, Orchos Tzaddikim, Kuzari, Sefer HaChinuch.",
    "collection.note.midrash": "Not included, because there is no free edition: Zohar, Mechilta.",
    "add.nothingMatches": "Nothing matches.",
    "add.oneChosen": "{name} chosen",
    "add.allChosen": "All {n} available chosen",
    "add.nChosen": "{n} chosen",
    "add.rangeHint": "Write it as in the sefer, for example {example}.",
    "add.endBeforeStart": "The end comes before the start.",
    "add.none": "None",
    "add.chooseSome": "Choose one or more seforim",
    "add.timeHint": "At this pace the whole of it takes about {n} hours of learning.",
    "add.summary": "{n} days · finishing {date}",
    "add.days": "days",
    "add.aboutMinutes": "About {n} minutes a day",
    "add.learnWith": "Learn with",
    "add.textAlone": "The text alone",
    "add.reviewDays": "Days",
    "add.lighterX": "lighter {day}",
    "add.starting": "Starting",
    "add.firstDay": "First day, {date}",
    "add.chooseFirstOff": "Choose the first day off",
    "add.remove": "Remove",
    "reminder.addFirst": "Add a sefer first; the reminder follows your plans.",
    "reminder.days": "On {days}, the days you learn, until {date}, when your last sefer is finished. Never on Shabbos or Yom Tov, and with an evening time not on Friday or Erev Yom Tov. If a plan changes, add it again.",
    "reminder.addSeferFirst": "Add a sefer first",
    "backup.copied": "Backup copied",
    "backup.selectAndCopy": "Select the text and copy it",
    "backup.notBackup": "This is not a learning calendar backup.",
    "backup.replaceAsk": "Replace the {n} plans on this phone with the {m} in the backup?",
    "backup.replace": "Replace",
    "backup.partFailed": "Part of this backup could not be read. Nothing was changed.",
    "backup.loaded": "Backup loaded",
    "load.catalogFailed": "Could not load the list of sefarim ({error}). Check the connection and try again.",
    "lesson.with": "with {names}",
    "lesson.day": "day",
    "lesson.finishing": "Finishing {date}",
    "lesson.wholeSchedule": "Whole schedule",
    "lesson.catchUp": "Catch up",
    "lesson.cantToday": "I can't learn today",
    "lesson.siyum": "Finished the whole sefer. Mazal tov!",
    "lesson.undoLast": "Undo the last day",
    "lesson.fromDate": "From {date}",
    "lesson.markDone": "Mark as done",
    "lesson.openSefaria": "Open on Sefaria",
    "lesson.onlyPart": "I only did part of it",
    "lesson.undo": "Undo",
    "lesson.done": "Done",
    "lesson.doneToday": "Done for today",
    "lesson.noLearning": "No learning on this day.",
    "lesson.next": "Next, {date}:",
    "lesson.learnAhead": "Learn ahead: mark {date} done",
    "status.finished": "Finished",
    "status.behindOne": "1 day behind",
    "status.behindMany": "{n} days behind",
    "status.ahead": "Ahead by {n}",
    "status.onSchedule": "On schedule",
    "added": "{name} added",
    "ask.save": "Save",
    "plan.paused": "Paused",
    "plan.pausedSince": "Paused since {date}. When you resume, the finish date moves later by the days paused.",
    "plan.resume": "Resume",
    "plan.resumed": "Resumed. What is left is shared out from today.",
    "group.summary": "{n} seforim together · finishing {date}",
    "group.pause": "Pause all",
    "group.resume": "Resume all",
    "group.pausedToast": "Paused. Nothing is due until you resume.",
    "group.move": "Move the finish date",
    "group.moveTitle": "New finish date for the whole group",
    "group.moved": "All of them now finish {date}",
    "group.changeOnToday": "This sefer is part of a group. Pause it or move its finish date together with the others, on the Today screen.",
    "kol.title": "Kol HaTorah in a year",
    "kol.short": "Shas, Mishnah, Rambam, Tanach and Shulchan Aruch, all finishing on the same day",
    "kol.intro": "One plan for each, all starting and finishing on the same dates. Remove any, or add another sefer.",
    "kol.optional": "optional",
    "kol.addOther": "Add another sefer",
    "kol.chooseOne": "Choose at least one.",
    "kol.endAfterStart": "The finish date must come after the start.",
    "kol.summary": "{n} plans, from {start} to {end}, each shared out evenly by its size.",
    "kol.create": "Start Kol HaTorah",
    "kol.making": "Preparing…",
    "kol.made": "{n} plans started together",
    "cycles.title": "Join a daily cycle",
    "cycles.short": "Daf Yomi, Mishnah Yomit or Rambam Yomi, learning what everyone learns today",
    "cycles.intro": "In a cycle everyone learns the same thing on the same day, so the days follow the cycle, not your settings.",
    "cycles.note.daf-yomi": "One daf a day",
    "cycles.note.mishnah-yomit": "Two mishnayos a day",
    "cycles.note.rambam-3": "Three perakim a day",
    "cycles.note.rambam-1": "One perek a day",
    "cycles.today": "Today: {name}",
    "cycles.ends": "This cycle finishes {date}",
    "cycles.join": "Join",
    "cycles.joined": "Joined",
    "cycles.welcome": "You joined {name}",
    "cycle.pill": "Daily cycle",
    "cycle.openPlace": "Open on Sefaria",
    "cycle.placeOnly": "Not in the app's texts: learn it from your own sefer.",
    "cycle.noChanges": "A daily cycle follows the cycle's own dates: everyone learns the same thing on the same day, so its days cannot be changed.",
    "review.pill": "Review",
    "review.switch": "This is a review (chazara)",
    "review.note": "Marked as review, at its own pace. Your first learning of it stays as it was.",
    "review.start": "Review what I learned (chazara)",
    "review.nothingYet": "Mark some days done first",
    "dedication.title": "Dedication (optional)",
    "dedication.none": "None",
    "dedication.iluiNishmas": "L'ilui nishmas",
    "dedication.refuah": "L'refuah shleimah",
    "dedication.namePlaceholder": "Name, e.g. Ploni ben Ploni",
    "dedication.save": "Save the dedication",
    "dedication.saved": "Dedication saved",
    "dedication.lineIlui": "l'ilui nishmas",
    "dedication.lineRefuah": "l'refuah shleimah",
    "suggest.title": "Before {name}",
    "suggest.sub": "Finish by Erev Yom Tov, {date}",
    "suggest.start": "Start",
    "suggest.hide": "Not this year",
    "suggest.noRange": "That part is not in the app",
    "account.framed": "Signing in works on the website, sefer-calendar.web.app, not in this preview. Plans here are kept on this phone only.",
    "account.offline": "Signing in needs a connection. Your plans are kept on this phone meanwhile, and move into your account when you sign in.",
    "account.linkSent": "We sent a sign-in link to {email}. Open it on this phone to sign in.",
    "account.typeEmail": "To finish signing in, type the email address the link was sent to, then tap the link in the email again.",
    "account.error.invalid-email": "That email address does not look right.",
    "account.error.network-request-failed": "No connection. Try again when the phone is online.",
    "account.error.invalid-action-code": "This sign-in link was already used or is too old. Ask for a new one.",
    "account.error.expired-action-code": "This sign-in link is too old. Ask for a new one.",
    "account.error.unauthorized-domain": "Signing in is not set up for this web address yet.",
    "account.error.operation-not-allowed": "This way of signing in is not turned on yet.",
    "account.error.other": "Could not sign in ({code}).",
    "account.yours": "your account",
    "account.unreachable": "Could not reach your account. Changes are kept on this phone and sent later.",
    "account.uploadedMany": "{n} plans from this phone saved to your account",
    "account.uploadedOne": "1 plan from this phone saved to your account",
    "account.saveFailed": "Could not save to your account. Changes are kept on this phone and sent later.",
    "account.nameSaved": "Name saved",
    "account.signedOut": "Signed out. Your plans stay in your account.",
    "account.deleteAsk": "Delete your account and all your plans? This cannot be undone.",
    "account.deleteYes": "Delete everything",
    "account.signInAgain": "For your safety, please sign in again, then delete.",
    "account.deleted": "Your account and plans were deleted.",
    "account.deleteFailed": "Could not delete the account. Try again when online.",
    "engine.siman": "siman {n}",
    "engine.time.2": " (the second time)",
    "engine.time.3": " (the third time)",
    "engine.time.4": " (the fourth time)",
    "engine.time.5": " (the fifth time)",
    "engine.time.6": " (the sixth time)",
    "engine.time.7": " (the seventh time)",
    "engine.time.8": " (the eighth time)",
    "engine.time.9": " (the ninth time)",
    "engine.time.10": " (the tenth time)",
    "engine.time.n": " (the {n}th time)",
    "engine.simanComma": "siman {n}, ",
    "engine.seifKatan": "{name} through {siman}se'if katan {n}",
    "engine.commThrough": "{name} through “{words}”",
    "engine.commOn": "{name} on {place}",
    "engine.fromWords": ", from the words “{words}”{time}",
    "engine.untilWords": ", until the words “{words}”{time}",
    "engine.toTheEndComma": ", to the end of {place}",
    "engine.aToB": "{a} to {b}",
    "engine.simanim": "simanim {a}–{b}",
    "engine.theEndOf": "the end of {place}",
    "engine.hasNo": "{name} has no {place}",
    "engine.whichSefer": "Write which sefer, for example {example}",
    "engine.noDaysSet": "No learning days are set",
    "engine.noDaysBefore": "There are no learning days before the finish date",
    "engine.tooSmall": "The daily amount is too small",
    "engine.outside": "The start and end are outside the sefer",
    "engine.oneDay": "Choose at least one learning day",
    "engine.endBeforeStart": "The finish date is before the start",
    "engine.chooseHow": "Choose a finish date, a daily amount or the minutes you have each day",
    "engine.insideDay": "Choose a place inside that day",
    "about.yerushalmi": "The Yerushalmi's text: <b>The Jerusalem Talmud, edition by Heinrich W. Guggenheimer</b> (Berlin, De Gruyter, 1999-2015), licensed <a href=\"https://creativecommons.org/licenses/by/3.0/\" target=\"_blank\" rel=\"noopener\">CC BY</a>, via <a href=\"https://www.sefaria.org/texts/Talmud/Yerushalmi\" target=\"_blank\" rel=\"noopener\">Sefaria</a>. The app keeps only the first few words of each place in it, and names places by perek and halacha.",
  } };

  let lang = "en";
  try { if (STRINGS[localStorage.getItem("learning-calendar-language")]) lang = localStorage.getItem("learning-calendar-language"); } catch (e) { /* English */ }

  function tr(key, vars) {
    let s = (STRINGS[lang] && STRINGS[lang][key]) ?? STRINGS.en[key];
    if (s === undefined) { if (global.console) console.warn("No text for", key); s = key; }
    return vars ? s.replace(/\{(\w+)\}/g, (m, k) => (vars[k] !== undefined ? vars[k] : m)) : s;
  }
  function applyStrings(root) {
    root = root || document;
    root.querySelectorAll("[data-t]").forEach((el) => { el.textContent = tr(el.dataset.t); });
    root.querySelectorAll("[data-t-html]").forEach((el) => { el.innerHTML = tr(el.dataset.tHtml); });
    for (const a of ["placeholder", "aria-label", "title", "alt"]) {
      root.querySelectorAll(`[data-t-${a}]`).forEach((el) => { el.setAttribute(a, tr(el.getAttribute(`data-t-${a}`))); });
    }
  }
  // Every screen is built to run right-to-left too: the page's direction follows the language.
  const RTL = ["he", "yi"];
  function applyLanguage() {
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL.includes(lang) ? "rtl" : "ltr";
    applyStrings();
  }

  global.STRINGS = STRINGS;
  global.tr = tr;
  global.LearnText = { tr, applyStrings, language: () => lang, locale: () => (lang === "he" ? "he-IL" : "en-US") };
  if (typeof document !== "undefined" && document.querySelector) applyLanguage();
  if (typeof module !== "undefined" && module.exports) module.exports = global.LearnText;
})(typeof window !== "undefined" ? window : globalThis);
